// Copies only the brand icons the site uses out of simple-icons into a tiny module,
// so the multi-megabyte package never reaches the bundle. Re-run after changing the list.
import { writeFileSync } from 'node:fs'
import * as si from 'simple-icons'

const used = ['siApachekafka', 'siCplusplus', 'siDocker', 'siFastapi', 'siFlask', 'siGin', 'siGit', 'siGithubactions', 'siGo',
  'siLangchain', 'siLeetcode', 'siLinux', 'siOpenrouter', 'siPostgresql', 'siPostman', 'siPrometheus', 'siPytest', 'siPython',
  'siRedis', 'siSqlalchemy', 'siSqlite']

const lines = used.map((k) => `export const ${k}: BrandIcon = ${JSON.stringify({ title: si[k].title, hex: si[k].hex, path: si[k].path })}`)
writeFileSync(
  new URL('../src/content/icons.generated.ts', import.meta.url),
  `// Generated by scripts/gen-icons.mjs from simple-icons (CC0). Do not edit by hand.\nexport type BrandIcon = { title: string; hex: string; path: string }\n\n${lines.join('\n')}\n`,
)
console.log(`wrote ${used.length} icons`)
