// Copies only the brand icons the site uses out of simple-icons into a tiny module,
// so the multi-megabyte package never reaches the bundle. Re-run after changing the list.
// Also writes them as an SVG sprite, so the page references each icon instead of inlining its path.
import { writeFileSync } from 'node:fs'
import * as si from 'simple-icons'

const used = ['siApachekafka', 'siCplusplus', 'siDocker', 'siFastapi', 'siFlask', 'siGin', 'siGit', 'siGithubactions', 'siGo',
  'siLangchain', 'siLeetcode', 'siLinux', 'siOpenrouter', 'siPostgresql', 'siPostman', 'siPrometheus', 'siPytest', 'siPython',
  'siRedis', 'siSqlalchemy', 'siSqlite']

const lines = used.map(
  (k) => `export const ${k}: BrandIcon = ${JSON.stringify({ title: si[k].title, slug: si[k].slug, hex: si[k].hex, path: si[k].path })}`,
)
writeFileSync(
  new URL('../src/content/icons.generated.ts', import.meta.url),
  `// Generated by scripts/gen-icons.mjs from simple-icons (CC0). Do not edit by hand.\nexport type BrandIcon = { title: string; slug: string; hex: string; path: string }\n\n${lines.join('\n')}\n`,
)
const symbols = used.map((k) => `<symbol id="${si[k].slug}" viewBox="0 0 24 24"><path d="${si[k].path}"/></symbol>`)
writeFileSync(
  new URL('../public/images/brand-icons.svg', import.meta.url),
  `<svg xmlns="http://www.w3.org/2000/svg">\n${symbols.join('\n')}\n</svg>\n`,
)
console.log(`wrote ${used.length} icons`)
